package com.bingblue.TaobaoTools.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AnalyzeStoreDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    public AnalyzeStoreDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAnalyzeStoreBillIdIsNull() {
            addCriterion("analyze_store_bill_id is null");
            return (Criteria) this;
        }

        public Criteria andAnalyzeStoreBillIdIsNotNull() {
            addCriterion("analyze_store_bill_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnalyzeStoreBillIdEqualTo(Long value) {
            addCriterion("analyze_store_bill_id =", value, "analyzeStoreBillId");
            return (Criteria) this;
        }

        public Criteria andAnalyzeStoreBillIdNotEqualTo(Long value) {
            addCriterion("analyze_store_bill_id <>", value, "analyzeStoreBillId");
            return (Criteria) this;
        }

        public Criteria andAnalyzeStoreBillIdGreaterThan(Long value) {
            addCriterion("analyze_store_bill_id >", value, "analyzeStoreBillId");
            return (Criteria) this;
        }

        public Criteria andAnalyzeStoreBillIdGreaterThanOrEqualTo(Long value) {
            addCriterion("analyze_store_bill_id >=", value, "analyzeStoreBillId");
            return (Criteria) this;
        }

        public Criteria andAnalyzeStoreBillIdLessThan(Long value) {
            addCriterion("analyze_store_bill_id <", value, "analyzeStoreBillId");
            return (Criteria) this;
        }

        public Criteria andAnalyzeStoreBillIdLessThanOrEqualTo(Long value) {
            addCriterion("analyze_store_bill_id <=", value, "analyzeStoreBillId");
            return (Criteria) this;
        }

        public Criteria andAnalyzeStoreBillIdIn(List<Long> values) {
            addCriterion("analyze_store_bill_id in", values, "analyzeStoreBillId");
            return (Criteria) this;
        }

        public Criteria andAnalyzeStoreBillIdNotIn(List<Long> values) {
            addCriterion("analyze_store_bill_id not in", values, "analyzeStoreBillId");
            return (Criteria) this;
        }

        public Criteria andAnalyzeStoreBillIdBetween(Long value1, Long value2) {
            addCriterion("analyze_store_bill_id between", value1, value2, "analyzeStoreBillId");
            return (Criteria) this;
        }

        public Criteria andAnalyzeStoreBillIdNotBetween(Long value1, Long value2) {
            addCriterion("analyze_store_bill_id not between", value1, value2, "analyzeStoreBillId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNull() {
            addCriterion("product_price is null");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNotNull() {
            addCriterion("product_price is not null");
            return (Criteria) this;
        }

        public Criteria andProductPriceEqualTo(Double value) {
            addCriterion("product_price =", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotEqualTo(Double value) {
            addCriterion("product_price <>", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThan(Double value) {
            addCriterion("product_price >", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("product_price >=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThan(Double value) {
            addCriterion("product_price <", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThanOrEqualTo(Double value) {
            addCriterion("product_price <=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceIn(List<Double> values) {
            addCriterion("product_price in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotIn(List<Double> values) {
            addCriterion("product_price not in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceBetween(Double value1, Double value2) {
            addCriterion("product_price between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotBetween(Double value1, Double value2) {
            addCriterion("product_price not between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductSaleQuantityIsNull() {
            addCriterion("product_sale_quantity is null");
            return (Criteria) this;
        }

        public Criteria andProductSaleQuantityIsNotNull() {
            addCriterion("product_sale_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andProductSaleQuantityEqualTo(Integer value) {
            addCriterion("product_sale_quantity =", value, "productSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andProductSaleQuantityNotEqualTo(Integer value) {
            addCriterion("product_sale_quantity <>", value, "productSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andProductSaleQuantityGreaterThan(Integer value) {
            addCriterion("product_sale_quantity >", value, "productSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andProductSaleQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_sale_quantity >=", value, "productSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andProductSaleQuantityLessThan(Integer value) {
            addCriterion("product_sale_quantity <", value, "productSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andProductSaleQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("product_sale_quantity <=", value, "productSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andProductSaleQuantityIn(List<Integer> values) {
            addCriterion("product_sale_quantity in", values, "productSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andProductSaleQuantityNotIn(List<Integer> values) {
            addCriterion("product_sale_quantity not in", values, "productSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andProductSaleQuantityBetween(Integer value1, Integer value2) {
            addCriterion("product_sale_quantity between", value1, value2, "productSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andProductSaleQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("product_sale_quantity not between", value1, value2, "productSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(Long value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(Long value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(Long value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(Long value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(Long value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(Long value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<Long> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<Long> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(Long value1, Long value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(Long value1, Long value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdIsNull() {
            addCriterion("product_taobao_id is null");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdIsNotNull() {
            addCriterion("product_taobao_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdEqualTo(String value) {
            addCriterion("product_taobao_id =", value, "productTaobaoId");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdNotEqualTo(String value) {
            addCriterion("product_taobao_id <>", value, "productTaobaoId");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdGreaterThan(String value) {
            addCriterion("product_taobao_id >", value, "productTaobaoId");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_taobao_id >=", value, "productTaobaoId");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdLessThan(String value) {
            addCriterion("product_taobao_id <", value, "productTaobaoId");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdLessThanOrEqualTo(String value) {
            addCriterion("product_taobao_id <=", value, "productTaobaoId");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdLike(String value) {
            addCriterion("product_taobao_id like", value, "productTaobaoId");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdNotLike(String value) {
            addCriterion("product_taobao_id not like", value, "productTaobaoId");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdIn(List<String> values) {
            addCriterion("product_taobao_id in", values, "productTaobaoId");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdNotIn(List<String> values) {
            addCriterion("product_taobao_id not in", values, "productTaobaoId");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdBetween(String value1, String value2) {
            addCriterion("product_taobao_id between", value1, value2, "productTaobaoId");
            return (Criteria) this;
        }

        public Criteria andProductTaobaoIdNotBetween(String value1, String value2) {
            addCriterion("product_taobao_id not between", value1, value2, "productTaobaoId");
            return (Criteria) this;
        }

        public Criteria andStoreNameIsNull() {
            addCriterion("store_name is null");
            return (Criteria) this;
        }

        public Criteria andStoreNameIsNotNull() {
            addCriterion("store_name is not null");
            return (Criteria) this;
        }

        public Criteria andStoreNameEqualTo(String value) {
            addCriterion("store_name =", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotEqualTo(String value) {
            addCriterion("store_name <>", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameGreaterThan(String value) {
            addCriterion("store_name >", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameGreaterThanOrEqualTo(String value) {
            addCriterion("store_name >=", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLessThan(String value) {
            addCriterion("store_name <", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLessThanOrEqualTo(String value) {
            addCriterion("store_name <=", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLike(String value) {
            addCriterion("store_name like", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotLike(String value) {
            addCriterion("store_name not like", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameIn(List<String> values) {
            addCriterion("store_name in", values, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotIn(List<String> values) {
            addCriterion("store_name not in", values, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameBetween(String value1, String value2) {
            addCriterion("store_name between", value1, value2, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotBetween(String value1, String value2) {
            addCriterion("store_name not between", value1, value2, "storeName");
            return (Criteria) this;
        }

        public Criteria andSourceDataIsNull() {
            addCriterion("source_data is null");
            return (Criteria) this;
        }

        public Criteria andSourceDataIsNotNull() {
            addCriterion("source_data is not null");
            return (Criteria) this;
        }

        public Criteria andSourceDataEqualTo(String value) {
            addCriterion("source_data =", value, "sourceData");
            return (Criteria) this;
        }

        public Criteria andSourceDataNotEqualTo(String value) {
            addCriterion("source_data <>", value, "sourceData");
            return (Criteria) this;
        }

        public Criteria andSourceDataGreaterThan(String value) {
            addCriterion("source_data >", value, "sourceData");
            return (Criteria) this;
        }

        public Criteria andSourceDataGreaterThanOrEqualTo(String value) {
            addCriterion("source_data >=", value, "sourceData");
            return (Criteria) this;
        }

        public Criteria andSourceDataLessThan(String value) {
            addCriterion("source_data <", value, "sourceData");
            return (Criteria) this;
        }

        public Criteria andSourceDataLessThanOrEqualTo(String value) {
            addCriterion("source_data <=", value, "sourceData");
            return (Criteria) this;
        }

        public Criteria andSourceDataLike(String value) {
            addCriterion("source_data like", value, "sourceData");
            return (Criteria) this;
        }

        public Criteria andSourceDataNotLike(String value) {
            addCriterion("source_data not like", value, "sourceData");
            return (Criteria) this;
        }

        public Criteria andSourceDataIn(List<String> values) {
            addCriterion("source_data in", values, "sourceData");
            return (Criteria) this;
        }

        public Criteria andSourceDataNotIn(List<String> values) {
            addCriterion("source_data not in", values, "sourceData");
            return (Criteria) this;
        }

        public Criteria andSourceDataBetween(String value1, String value2) {
            addCriterion("source_data between", value1, value2, "sourceData");
            return (Criteria) this;
        }

        public Criteria andSourceDataNotBetween(String value1, String value2) {
            addCriterion("source_data not between", value1, value2, "sourceData");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}