package com.bingblue.TaobaoTools.pojo;

import java.util.Date;

public class AnalyzeStoreDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestoredetail.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestoredetail.analyze_store_bill_id
     *
     * @mbg.generated
     */
    private Long analyzeStoreBillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestoredetail.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestoredetail.product_price
     *
     * @mbg.generated
     */
    private Double productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestoredetail.product_sale_quantity
     *
     * @mbg.generated
     */
    private Integer productSaleQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestoredetail.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestoredetail.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestoredetail.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestoredetail.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestoredetail.product_taobao_id
     *
     * @mbg.generated
     */
    private String productTaobaoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestoredetail.store_name
     *
     * @mbg.generated
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestoredetail.source_data
     *
     * @mbg.generated
     */
    private String sourceData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestoredetail.id
     *
     * @return the value of t_analyzestoredetail.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestoredetail.id
     *
     * @param id the value for t_analyzestoredetail.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestoredetail.analyze_store_bill_id
     *
     * @return the value of t_analyzestoredetail.analyze_store_bill_id
     *
     * @mbg.generated
     */
    public Long getAnalyzeStoreBillId() {
        return analyzeStoreBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestoredetail.analyze_store_bill_id
     *
     * @param analyzeStoreBillId the value for t_analyzestoredetail.analyze_store_bill_id
     *
     * @mbg.generated
     */
    public void setAnalyzeStoreBillId(Long analyzeStoreBillId) {
        this.analyzeStoreBillId = analyzeStoreBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestoredetail.product_name
     *
     * @return the value of t_analyzestoredetail.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestoredetail.product_name
     *
     * @param productName the value for t_analyzestoredetail.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestoredetail.product_price
     *
     * @return the value of t_analyzestoredetail.product_price
     *
     * @mbg.generated
     */
    public Double getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestoredetail.product_price
     *
     * @param productPrice the value for t_analyzestoredetail.product_price
     *
     * @mbg.generated
     */
    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestoredetail.product_sale_quantity
     *
     * @return the value of t_analyzestoredetail.product_sale_quantity
     *
     * @mbg.generated
     */
    public Integer getProductSaleQuantity() {
        return productSaleQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestoredetail.product_sale_quantity
     *
     * @param productSaleQuantity the value for t_analyzestoredetail.product_sale_quantity
     *
     * @mbg.generated
     */
    public void setProductSaleQuantity(Integer productSaleQuantity) {
        this.productSaleQuantity = productSaleQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestoredetail.create_date
     *
     * @return the value of t_analyzestoredetail.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestoredetail.create_date
     *
     * @param createDate the value for t_analyzestoredetail.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestoredetail.remark
     *
     * @return the value of t_analyzestoredetail.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestoredetail.remark
     *
     * @param remark the value for t_analyzestoredetail.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestoredetail.user_id
     *
     * @return the value of t_analyzestoredetail.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestoredetail.user_id
     *
     * @param userId the value for t_analyzestoredetail.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestoredetail.member_id
     *
     * @return the value of t_analyzestoredetail.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestoredetail.member_id
     *
     * @param memberId the value for t_analyzestoredetail.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestoredetail.product_taobao_id
     *
     * @return the value of t_analyzestoredetail.product_taobao_id
     *
     * @mbg.generated
     */
    public String getProductTaobaoId() {
        return productTaobaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestoredetail.product_taobao_id
     *
     * @param productTaobaoId the value for t_analyzestoredetail.product_taobao_id
     *
     * @mbg.generated
     */
    public void setProductTaobaoId(String productTaobaoId) {
        this.productTaobaoId = productTaobaoId == null ? null : productTaobaoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestoredetail.store_name
     *
     * @return the value of t_analyzestoredetail.store_name
     *
     * @mbg.generated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestoredetail.store_name
     *
     * @param storeName the value for t_analyzestoredetail.store_name
     *
     * @mbg.generated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestoredetail.source_data
     *
     * @return the value of t_analyzestoredetail.source_data
     *
     * @mbg.generated
     */
    public String getSourceData() {
        return sourceData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestoredetail.source_data
     *
     * @param sourceData the value for t_analyzestoredetail.source_data
     *
     * @mbg.generated
     */
    public void setSourceData(String sourceData) {
        this.sourceData = sourceData == null ? null : sourceData.trim();
    }
}