package com.bingblue.TaobaoTools.pojo;

import java.util.Date;
import java.util.List;

public class AnalyzeStoreBill {
    
    private List<AnalyzeStoreDetail> analyzeStoreDetails;
    public List<AnalyzeStoreDetail> getAnalyzeStoreDetails() {
        return analyzeStoreDetails;
    }

    public void setAnalyzeStoreDetails(List<AnalyzeStoreDetail> analyzeStoreDetails) {
        this.analyzeStoreDetails = analyzeStoreDetails;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestorebill.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestorebill.happen_date
     *
     * @mbg.generated
     */
    private Date happenDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestorebill.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestorebill.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestorebill.catch_url
     *
     * @mbg.generated
     */
    private String catchUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestorebill.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestorebill.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestorebill.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestorebill.done_date
     *
     * @mbg.generated
     */
    private Date doneDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestorebill.catch_remark
     *
     * @mbg.generated
     */
    private String catchRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestorebill.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_analyzestorebill.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestorebill.id
     *
     * @return the value of t_analyzestorebill.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestorebill.id
     *
     * @param id the value for t_analyzestorebill.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestorebill.happen_date
     *
     * @return the value of t_analyzestorebill.happen_date
     *
     * @mbg.generated
     */
    public Date getHappenDate() {
        return happenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestorebill.happen_date
     *
     * @param happenDate the value for t_analyzestorebill.happen_date
     *
     * @mbg.generated
     */
    public void setHappenDate(Date happenDate) {
        this.happenDate = happenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestorebill.user_id
     *
     * @return the value of t_analyzestorebill.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestorebill.user_id
     *
     * @param userId the value for t_analyzestorebill.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestorebill.status
     *
     * @return the value of t_analyzestorebill.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestorebill.status
     *
     * @param status the value for t_analyzestorebill.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestorebill.catch_url
     *
     * @return the value of t_analyzestorebill.catch_url
     *
     * @mbg.generated
     */
    public String getCatchUrl() {
        return catchUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestorebill.catch_url
     *
     * @param catchUrl the value for t_analyzestorebill.catch_url
     *
     * @mbg.generated
     */
    public void setCatchUrl(String catchUrl) {
        this.catchUrl = catchUrl == null ? null : catchUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestorebill.create_date
     *
     * @return the value of t_analyzestorebill.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestorebill.create_date
     *
     * @param createDate the value for t_analyzestorebill.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestorebill.remark
     *
     * @return the value of t_analyzestorebill.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestorebill.remark
     *
     * @param remark the value for t_analyzestorebill.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestorebill.member_id
     *
     * @return the value of t_analyzestorebill.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestorebill.member_id
     *
     * @param memberId the value for t_analyzestorebill.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestorebill.done_date
     *
     * @return the value of t_analyzestorebill.done_date
     *
     * @mbg.generated
     */
    public Date getDoneDate() {
        return doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestorebill.done_date
     *
     * @param doneDate the value for t_analyzestorebill.done_date
     *
     * @mbg.generated
     */
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestorebill.catch_remark
     *
     * @return the value of t_analyzestorebill.catch_remark
     *
     * @mbg.generated
     */
    public String getCatchRemark() {
        return catchRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestorebill.catch_remark
     *
     * @param catchRemark the value for t_analyzestorebill.catch_remark
     *
     * @mbg.generated
     */
    public void setCatchRemark(String catchRemark) {
        this.catchRemark = catchRemark == null ? null : catchRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestorebill.name
     *
     * @return the value of t_analyzestorebill.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestorebill.name
     *
     * @param name the value for t_analyzestorebill.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_analyzestorebill.shop_id
     *
     * @return the value of t_analyzestorebill.shop_id
     *
     * @mbg.generated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_analyzestorebill.shop_id
     *
     * @param shopId the value for t_analyzestorebill.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }
}