package com.bingblue.TaobaoTools.pojo;

public class LocalCookie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.expires_at
     *
     * @mbg.generated
     */
    private Long expiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.domain
     *
     * @mbg.generated
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.secure
     *
     * @mbg.generated
     */
    private Boolean secure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.http_only
     *
     * @mbg.generated
     */
    private Boolean httpOnly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.persistent
     *
     * @mbg.generated
     */
    private Boolean persistent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.host_only
     *
     * @mbg.generated
     */
    private Boolean hostOnly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.client_id
     *
     * @mbg.generated
     */
    private Long clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_localcookie.host
     *
     * @mbg.generated
     */
    private String host;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.id
     *
     * @return the value of t_localcookie.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.id
     *
     * @param id the value for t_localcookie.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.name
     *
     * @return the value of t_localcookie.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.name
     *
     * @param name the value for t_localcookie.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.value
     *
     * @return the value of t_localcookie.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.value
     *
     * @param value the value for t_localcookie.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.expires_at
     *
     * @return the value of t_localcookie.expires_at
     *
     * @mbg.generated
     */
    public Long getExpiresAt() {
        return expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.expires_at
     *
     * @param expiresAt the value for t_localcookie.expires_at
     *
     * @mbg.generated
     */
    public void setExpiresAt(Long expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.domain
     *
     * @return the value of t_localcookie.domain
     *
     * @mbg.generated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.domain
     *
     * @param domain the value for t_localcookie.domain
     *
     * @mbg.generated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.path
     *
     * @return the value of t_localcookie.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.path
     *
     * @param path the value for t_localcookie.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.secure
     *
     * @return the value of t_localcookie.secure
     *
     * @mbg.generated
     */
    public Boolean getSecure() {
        return secure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.secure
     *
     * @param secure the value for t_localcookie.secure
     *
     * @mbg.generated
     */
    public void setSecure(Boolean secure) {
        this.secure = secure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.http_only
     *
     * @return the value of t_localcookie.http_only
     *
     * @mbg.generated
     */
    public Boolean getHttpOnly() {
        return httpOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.http_only
     *
     * @param httpOnly the value for t_localcookie.http_only
     *
     * @mbg.generated
     */
    public void setHttpOnly(Boolean httpOnly) {
        this.httpOnly = httpOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.persistent
     *
     * @return the value of t_localcookie.persistent
     *
     * @mbg.generated
     */
    public Boolean getPersistent() {
        return persistent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.persistent
     *
     * @param persistent the value for t_localcookie.persistent
     *
     * @mbg.generated
     */
    public void setPersistent(Boolean persistent) {
        this.persistent = persistent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.host_only
     *
     * @return the value of t_localcookie.host_only
     *
     * @mbg.generated
     */
    public Boolean getHostOnly() {
        return hostOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.host_only
     *
     * @param hostOnly the value for t_localcookie.host_only
     *
     * @mbg.generated
     */
    public void setHostOnly(Boolean hostOnly) {
        this.hostOnly = hostOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.client_id
     *
     * @return the value of t_localcookie.client_id
     *
     * @mbg.generated
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.client_id
     *
     * @param clientId the value for t_localcookie.client_id
     *
     * @mbg.generated
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.type
     *
     * @return the value of t_localcookie.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.type
     *
     * @param type the value for t_localcookie.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_localcookie.host
     *
     * @return the value of t_localcookie.host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_localcookie.host
     *
     * @param host the value for t_localcookie.host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }
}