package com.bingblue.TaobaoTools.pojo;

import java.util.Date;
import java.util.List;

public class ManyOrderBill {
    private List<ManyOrderDetail> manyOrderDetails;
    public List<ManyOrderDetail> getManyOrderDetails() {
        return manyOrderDetails;
    }

    public void setManyOrderDetails(List<ManyOrderDetail> manyOrderDetails) {
        this.manyOrderDetails = manyOrderDetails;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderbill.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderbill.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderbill.short_link
     *
     * @mbg.generated
     */
    private String shortLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderbill.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderbill.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderbill.product_url
     *
     * @mbg.generated
     */
    private String productUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderbill.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderbill.id
     *
     * @return the value of t_manyorderbill.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderbill.id
     *
     * @param id the value for t_manyorderbill.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderbill.user_id
     *
     * @return the value of t_manyorderbill.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderbill.user_id
     *
     * @param userId the value for t_manyorderbill.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderbill.short_link
     *
     * @return the value of t_manyorderbill.short_link
     *
     * @mbg.generated
     */
    public String getShortLink() {
        return shortLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderbill.short_link
     *
     * @param shortLink the value for t_manyorderbill.short_link
     *
     * @mbg.generated
     */
    public void setShortLink(String shortLink) {
        this.shortLink = shortLink == null ? null : shortLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderbill.create_date
     *
     * @return the value of t_manyorderbill.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderbill.create_date
     *
     * @param createDate the value for t_manyorderbill.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderbill.remark
     *
     * @return the value of t_manyorderbill.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderbill.remark
     *
     * @param remark the value for t_manyorderbill.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderbill.product_url
     *
     * @return the value of t_manyorderbill.product_url
     *
     * @mbg.generated
     */
    public String getProductUrl() {
        return productUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderbill.product_url
     *
     * @param productUrl the value for t_manyorderbill.product_url
     *
     * @mbg.generated
     */
    public void setProductUrl(String productUrl) {
        this.productUrl = productUrl == null ? null : productUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderbill.member_id
     *
     * @return the value of t_manyorderbill.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderbill.member_id
     *
     * @param memberId the value for t_manyorderbill.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }
}