package com.bingblue.TaobaoTools.pojo;

public class ManyOrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderdetail.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderdetail.head_id
     *
     * @mbg.generated
     */
    private Long headId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderdetail.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderdetail.limit_click_quantity
     *
     * @mbg.generated
     */
    private Integer limitClickQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderdetail.click_quantity
     *
     * @mbg.generated
     */
    private Integer clickQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderdetail.click_count
     *
     * @mbg.generated
     */
    private Integer clickCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderdetail.product_url
     *
     * @mbg.generated
     */
    private String productUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manyorderdetail.taobao_word_id
     *
     * @mbg.generated
     */
    private Long taobaoWordId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderdetail.id
     *
     * @return the value of t_manyorderdetail.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderdetail.id
     *
     * @param id the value for t_manyorderdetail.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderdetail.head_id
     *
     * @return the value of t_manyorderdetail.head_id
     *
     * @mbg.generated
     */
    public Long getHeadId() {
        return headId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderdetail.head_id
     *
     * @param headId the value for t_manyorderdetail.head_id
     *
     * @mbg.generated
     */
    public void setHeadId(Long headId) {
        this.headId = headId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderdetail.keywords
     *
     * @return the value of t_manyorderdetail.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderdetail.keywords
     *
     * @param keywords the value for t_manyorderdetail.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderdetail.limit_click_quantity
     *
     * @return the value of t_manyorderdetail.limit_click_quantity
     *
     * @mbg.generated
     */
    public Integer getLimitClickQuantity() {
        return limitClickQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderdetail.limit_click_quantity
     *
     * @param limitClickQuantity the value for t_manyorderdetail.limit_click_quantity
     *
     * @mbg.generated
     */
    public void setLimitClickQuantity(Integer limitClickQuantity) {
        this.limitClickQuantity = limitClickQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderdetail.click_quantity
     *
     * @return the value of t_manyorderdetail.click_quantity
     *
     * @mbg.generated
     */
    public Integer getClickQuantity() {
        return clickQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderdetail.click_quantity
     *
     * @param clickQuantity the value for t_manyorderdetail.click_quantity
     *
     * @mbg.generated
     */
    public void setClickQuantity(Integer clickQuantity) {
        this.clickQuantity = clickQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderdetail.click_count
     *
     * @return the value of t_manyorderdetail.click_count
     *
     * @mbg.generated
     */
    public Integer getClickCount() {
        return clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderdetail.click_count
     *
     * @param clickCount the value for t_manyorderdetail.click_count
     *
     * @mbg.generated
     */
    public void setClickCount(Integer clickCount) {
        this.clickCount = clickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderdetail.product_url
     *
     * @return the value of t_manyorderdetail.product_url
     *
     * @mbg.generated
     */
    public String getProductUrl() {
        return productUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderdetail.product_url
     *
     * @param productUrl the value for t_manyorderdetail.product_url
     *
     * @mbg.generated
     */
    public void setProductUrl(String productUrl) {
        this.productUrl = productUrl == null ? null : productUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manyorderdetail.taobao_word_id
     *
     * @return the value of t_manyorderdetail.taobao_word_id
     *
     * @mbg.generated
     */
    public Long getTaobaoWordId() {
        return taobaoWordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manyorderdetail.taobao_word_id
     *
     * @param taobaoWordId the value for t_manyorderdetail.taobao_word_id
     *
     * @mbg.generated
     */
    public void setTaobaoWordId(Long taobaoWordId) {
        this.taobaoWordId = taobaoWordId;
    }
}