package com.bingblue.TaobaoTools.pojo;

import java.util.Date;

public class StuckFirstScreenBill {
    //mycode start
    private TaobaoWord taobaoWord;

    public TaobaoWord getTaobaoWord() {
        return taobaoWord;
    }

    public void setTaobaoWord(TaobaoWord taobaoWord) {
        this.taobaoWord = taobaoWord;
    }
    
    //mycode end
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuckfirstscreenbill.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuckfirstscreenbill.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuckfirstscreenbill.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuckfirstscreenbill.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuckfirstscreenbill.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuckfirstscreenbill.taobao_word_id
     *
     * @mbg.generated
     */
    private Long taobaoWordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuckfirstscreenbill.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuckfirstscreenbill.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stuckfirstscreenbill.competitor
     *
     * @mbg.generated
     */
    private Boolean competitor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuckfirstscreenbill.id
     *
     * @return the value of t_stuckfirstscreenbill.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuckfirstscreenbill.id
     *
     * @param id the value for t_stuckfirstscreenbill.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuckfirstscreenbill.keywords
     *
     * @return the value of t_stuckfirstscreenbill.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuckfirstscreenbill.keywords
     *
     * @param keywords the value for t_stuckfirstscreenbill.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuckfirstscreenbill.product_id
     *
     * @return the value of t_stuckfirstscreenbill.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuckfirstscreenbill.product_id
     *
     * @param productId the value for t_stuckfirstscreenbill.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuckfirstscreenbill.create_date
     *
     * @return the value of t_stuckfirstscreenbill.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuckfirstscreenbill.create_date
     *
     * @param createDate the value for t_stuckfirstscreenbill.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuckfirstscreenbill.member_id
     *
     * @return the value of t_stuckfirstscreenbill.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuckfirstscreenbill.member_id
     *
     * @param memberId the value for t_stuckfirstscreenbill.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuckfirstscreenbill.taobao_word_id
     *
     * @return the value of t_stuckfirstscreenbill.taobao_word_id
     *
     * @mbg.generated
     */
    public Long getTaobaoWordId() {
        return taobaoWordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuckfirstscreenbill.taobao_word_id
     *
     * @param taobaoWordId the value for t_stuckfirstscreenbill.taobao_word_id
     *
     * @mbg.generated
     */
    public void setTaobaoWordId(Long taobaoWordId) {
        this.taobaoWordId = taobaoWordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuckfirstscreenbill.status
     *
     * @return the value of t_stuckfirstscreenbill.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuckfirstscreenbill.status
     *
     * @param status the value for t_stuckfirstscreenbill.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuckfirstscreenbill.remark
     *
     * @return the value of t_stuckfirstscreenbill.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuckfirstscreenbill.remark
     *
     * @param remark the value for t_stuckfirstscreenbill.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stuckfirstscreenbill.competitor
     *
     * @return the value of t_stuckfirstscreenbill.competitor
     *
     * @mbg.generated
     */
    public Boolean getCompetitor() {
        return competitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stuckfirstscreenbill.competitor
     *
     * @param competitor the value for t_stuckfirstscreenbill.competitor
     *
     * @mbg.generated
     */
    public void setCompetitor(Boolean competitor) {
        this.competitor = competitor;
    }
}