package com.bingblue.TaobaoTools.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaobaoShopProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    public TaobaoShopProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPIdIsNull() {
            addCriterion("p_id is null");
            return (Criteria) this;
        }

        public Criteria andPIdIsNotNull() {
            addCriterion("p_id is not null");
            return (Criteria) this;
        }

        public Criteria andPIdEqualTo(String value) {
            addCriterion("p_id =", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotEqualTo(String value) {
            addCriterion("p_id <>", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdGreaterThan(String value) {
            addCriterion("p_id >", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdGreaterThanOrEqualTo(String value) {
            addCriterion("p_id >=", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLessThan(String value) {
            addCriterion("p_id <", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLessThanOrEqualTo(String value) {
            addCriterion("p_id <=", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLike(String value) {
            addCriterion("p_id like", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotLike(String value) {
            addCriterion("p_id not like", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdIn(List<String> values) {
            addCriterion("p_id in", values, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotIn(List<String> values) {
            addCriterion("p_id not in", values, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdBetween(String value1, String value2) {
            addCriterion("p_id between", value1, value2, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotBetween(String value1, String value2) {
            addCriterion("p_id not between", value1, value2, "pId");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Double value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Double value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Double value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Double value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Double value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Double> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Double> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Double value1, Double value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Double value1, Double value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andTotalSaleQuantityIsNull() {
            addCriterion("total_sale_quantity is null");
            return (Criteria) this;
        }

        public Criteria andTotalSaleQuantityIsNotNull() {
            addCriterion("total_sale_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andTotalSaleQuantityEqualTo(Integer value) {
            addCriterion("total_sale_quantity =", value, "totalSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalSaleQuantityNotEqualTo(Integer value) {
            addCriterion("total_sale_quantity <>", value, "totalSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalSaleQuantityGreaterThan(Integer value) {
            addCriterion("total_sale_quantity >", value, "totalSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalSaleQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_sale_quantity >=", value, "totalSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalSaleQuantityLessThan(Integer value) {
            addCriterion("total_sale_quantity <", value, "totalSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalSaleQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("total_sale_quantity <=", value, "totalSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalSaleQuantityIn(List<Integer> values) {
            addCriterion("total_sale_quantity in", values, "totalSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalSaleQuantityNotIn(List<Integer> values) {
            addCriterion("total_sale_quantity not in", values, "totalSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalSaleQuantityBetween(Integer value1, Integer value2) {
            addCriterion("total_sale_quantity between", value1, value2, "totalSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalSaleQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("total_sale_quantity not between", value1, value2, "totalSaleQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCommentQuantityIsNull() {
            addCriterion("total_comment_quantity is null");
            return (Criteria) this;
        }

        public Criteria andTotalCommentQuantityIsNotNull() {
            addCriterion("total_comment_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCommentQuantityEqualTo(Integer value) {
            addCriterion("total_comment_quantity =", value, "totalCommentQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCommentQuantityNotEqualTo(Integer value) {
            addCriterion("total_comment_quantity <>", value, "totalCommentQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCommentQuantityGreaterThan(Integer value) {
            addCriterion("total_comment_quantity >", value, "totalCommentQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCommentQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_comment_quantity >=", value, "totalCommentQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCommentQuantityLessThan(Integer value) {
            addCriterion("total_comment_quantity <", value, "totalCommentQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCommentQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("total_comment_quantity <=", value, "totalCommentQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCommentQuantityIn(List<Integer> values) {
            addCriterion("total_comment_quantity in", values, "totalCommentQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCommentQuantityNotIn(List<Integer> values) {
            addCriterion("total_comment_quantity not in", values, "totalCommentQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCommentQuantityBetween(Integer value1, Integer value2) {
            addCriterion("total_comment_quantity between", value1, value2, "totalCommentQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalCommentQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("total_comment_quantity not between", value1, value2, "totalCommentQuantity");
            return (Criteria) this;
        }

        public Criteria andTotalSaleIsNull() {
            addCriterion("total_sale is null");
            return (Criteria) this;
        }

        public Criteria andTotalSaleIsNotNull() {
            addCriterion("total_sale is not null");
            return (Criteria) this;
        }

        public Criteria andTotalSaleEqualTo(Double value) {
            addCriterion("total_sale =", value, "totalSale");
            return (Criteria) this;
        }

        public Criteria andTotalSaleNotEqualTo(Double value) {
            addCriterion("total_sale <>", value, "totalSale");
            return (Criteria) this;
        }

        public Criteria andTotalSaleGreaterThan(Double value) {
            addCriterion("total_sale >", value, "totalSale");
            return (Criteria) this;
        }

        public Criteria andTotalSaleGreaterThanOrEqualTo(Double value) {
            addCriterion("total_sale >=", value, "totalSale");
            return (Criteria) this;
        }

        public Criteria andTotalSaleLessThan(Double value) {
            addCriterion("total_sale <", value, "totalSale");
            return (Criteria) this;
        }

        public Criteria andTotalSaleLessThanOrEqualTo(Double value) {
            addCriterion("total_sale <=", value, "totalSale");
            return (Criteria) this;
        }

        public Criteria andTotalSaleIn(List<Double> values) {
            addCriterion("total_sale in", values, "totalSale");
            return (Criteria) this;
        }

        public Criteria andTotalSaleNotIn(List<Double> values) {
            addCriterion("total_sale not in", values, "totalSale");
            return (Criteria) this;
        }

        public Criteria andTotalSaleBetween(Double value1, Double value2) {
            addCriterion("total_sale between", value1, value2, "totalSale");
            return (Criteria) this;
        }

        public Criteria andTotalSaleNotBetween(Double value1, Double value2) {
            addCriterion("total_sale not between", value1, value2, "totalSale");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateIsNull() {
            addCriterion("happen_date is null");
            return (Criteria) this;
        }

        public Criteria andHappenDateIsNotNull() {
            addCriterion("happen_date is not null");
            return (Criteria) this;
        }

        public Criteria andHappenDateEqualTo(Date value) {
            addCriterion("happen_date =", value, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateNotEqualTo(Date value) {
            addCriterion("happen_date <>", value, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateGreaterThan(Date value) {
            addCriterion("happen_date >", value, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateGreaterThanOrEqualTo(Date value) {
            addCriterion("happen_date >=", value, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateLessThan(Date value) {
            addCriterion("happen_date <", value, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateLessThanOrEqualTo(Date value) {
            addCriterion("happen_date <=", value, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateIn(List<Date> values) {
            addCriterion("happen_date in", values, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateNotIn(List<Date> values) {
            addCriterion("happen_date not in", values, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateBetween(Date value1, Date value2) {
            addCriterion("happen_date between", value1, value2, "happenDate");
            return (Criteria) this;
        }

        public Criteria andHappenDateNotBetween(Date value1, Date value2) {
            addCriterion("happen_date not between", value1, value2, "happenDate");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Long value) {
            addCriterion("shop_id =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Long value) {
            addCriterion("shop_id <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Long value) {
            addCriterion("shop_id >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Long value) {
            addCriterion("shop_id >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Long value) {
            addCriterion("shop_id <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Long value) {
            addCriterion("shop_id <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Long> values) {
            addCriterion("shop_id in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Long> values) {
            addCriterion("shop_id not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Long value1, Long value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Long value1, Long value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}