package com.bingblue.TaobaoTools.pojo;

import java.util.Date;

public class TaobaoWord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoword.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoword.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoword.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoword.text
     *
     * @mbg.generated
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoword.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoword.logo_url
     *
     * @mbg.generated
     */
    private String logoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoword.ext
     *
     * @mbg.generated
     */
    private String ext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoword.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoword.tpwd
     *
     * @mbg.generated
     */
    private String tpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoword.failure_date
     *
     * @mbg.generated
     */
    private Date failureDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoword.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoword.id
     *
     * @return the value of t_taobaoword.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoword.id
     *
     * @param id the value for t_taobaoword.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoword.create_date
     *
     * @return the value of t_taobaoword.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoword.create_date
     *
     * @param createDate the value for t_taobaoword.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoword.status
     *
     * @return the value of t_taobaoword.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoword.status
     *
     * @param status the value for t_taobaoword.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoword.text
     *
     * @return the value of t_taobaoword.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoword.text
     *
     * @param text the value for t_taobaoword.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoword.remark
     *
     * @return the value of t_taobaoword.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoword.remark
     *
     * @param remark the value for t_taobaoword.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoword.logo_url
     *
     * @return the value of t_taobaoword.logo_url
     *
     * @mbg.generated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoword.logo_url
     *
     * @param logoUrl the value for t_taobaoword.logo_url
     *
     * @mbg.generated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoword.ext
     *
     * @return the value of t_taobaoword.ext
     *
     * @mbg.generated
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoword.ext
     *
     * @param ext the value for t_taobaoword.ext
     *
     * @mbg.generated
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoword.url
     *
     * @return the value of t_taobaoword.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoword.url
     *
     * @param url the value for t_taobaoword.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoword.tpwd
     *
     * @return the value of t_taobaoword.tpwd
     *
     * @mbg.generated
     */
    public String getTpwd() {
        return tpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoword.tpwd
     *
     * @param tpwd the value for t_taobaoword.tpwd
     *
     * @mbg.generated
     */
    public void setTpwd(String tpwd) {
        this.tpwd = tpwd == null ? null : tpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoword.failure_date
     *
     * @return the value of t_taobaoword.failure_date
     *
     * @mbg.generated
     */
    public Date getFailureDate() {
        return failureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoword.failure_date
     *
     * @param failureDate the value for t_taobaoword.failure_date
     *
     * @mbg.generated
     */
    public void setFailureDate(Date failureDate) {
        this.failureDate = failureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoword.member_id
     *
     * @return the value of t_taobaoword.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoword.member_id
     *
     * @param memberId the value for t_taobaoword.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }
}