package com.bingblue.TaobaoTools.pojo;

import java.util.Date;

public class TaobaoShop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoshop.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoshop.shop_id
     *
     * @mbg.generated
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoshop.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoshop.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoshop.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoshop.lately_capture_date
     *
     * @mbg.generated
     */
    private Date latelyCaptureDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoshop.total_sale_quantity
     *
     * @mbg.generated
     */
    private Integer totalSaleQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaoshop.total_sale
     *
     * @mbg.generated
     */
    private Double totalSale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoshop.id
     *
     * @return the value of t_taobaoshop.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoshop.id
     *
     * @param id the value for t_taobaoshop.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoshop.shop_id
     *
     * @return the value of t_taobaoshop.shop_id
     *
     * @mbg.generated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoshop.shop_id
     *
     * @param shopId the value for t_taobaoshop.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoshop.name
     *
     * @return the value of t_taobaoshop.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoshop.name
     *
     * @param name the value for t_taobaoshop.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoshop.url
     *
     * @return the value of t_taobaoshop.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoshop.url
     *
     * @param url the value for t_taobaoshop.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoshop.type
     *
     * @return the value of t_taobaoshop.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoshop.type
     *
     * @param type the value for t_taobaoshop.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoshop.lately_capture_date
     *
     * @return the value of t_taobaoshop.lately_capture_date
     *
     * @mbg.generated
     */
    public Date getLatelyCaptureDate() {
        return latelyCaptureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoshop.lately_capture_date
     *
     * @param latelyCaptureDate the value for t_taobaoshop.lately_capture_date
     *
     * @mbg.generated
     */
    public void setLatelyCaptureDate(Date latelyCaptureDate) {
        this.latelyCaptureDate = latelyCaptureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoshop.total_sale_quantity
     *
     * @return the value of t_taobaoshop.total_sale_quantity
     *
     * @mbg.generated
     */
    public Integer getTotalSaleQuantity() {
        return totalSaleQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoshop.total_sale_quantity
     *
     * @param totalSaleQuantity the value for t_taobaoshop.total_sale_quantity
     *
     * @mbg.generated
     */
    public void setTotalSaleQuantity(Integer totalSaleQuantity) {
        this.totalSaleQuantity = totalSaleQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaoshop.total_sale
     *
     * @return the value of t_taobaoshop.total_sale
     *
     * @mbg.generated
     */
    public Double getTotalSale() {
        return totalSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaoshop.total_sale
     *
     * @param totalSale the value for t_taobaoshop.total_sale
     *
     * @mbg.generated
     */
    public void setTotalSale(Double totalSale) {
        this.totalSale = totalSale;
    }
}