package com.bingblue.TaobaoTools.pojo;

import java.util.Date;

public class TaobaoWordBill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaowordbill.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaowordbill.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaowordbill.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaowordbill.taobao_word_id
     *
     * @mbg.generated
     */
    private Long taobaoWordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaowordbill.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaowordbill.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaowordbill.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_taobaowordbill.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaowordbill.id
     *
     * @return the value of t_taobaowordbill.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaowordbill.id
     *
     * @param id the value for t_taobaowordbill.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaowordbill.create_date
     *
     * @return the value of t_taobaowordbill.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaowordbill.create_date
     *
     * @param createDate the value for t_taobaowordbill.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaowordbill.member_id
     *
     * @return the value of t_taobaowordbill.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaowordbill.member_id
     *
     * @param memberId the value for t_taobaowordbill.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaowordbill.taobao_word_id
     *
     * @return the value of t_taobaowordbill.taobao_word_id
     *
     * @mbg.generated
     */
    public Long getTaobaoWordId() {
        return taobaoWordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaowordbill.taobao_word_id
     *
     * @param taobaoWordId the value for t_taobaowordbill.taobao_word_id
     *
     * @mbg.generated
     */
    public void setTaobaoWordId(Long taobaoWordId) {
        this.taobaoWordId = taobaoWordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaowordbill.remark
     *
     * @return the value of t_taobaowordbill.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaowordbill.remark
     *
     * @param remark the value for t_taobaowordbill.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaowordbill.status
     *
     * @return the value of t_taobaowordbill.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaowordbill.status
     *
     * @param status the value for t_taobaowordbill.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaowordbill.user_id
     *
     * @return the value of t_taobaowordbill.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaowordbill.user_id
     *
     * @param userId the value for t_taobaowordbill.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_taobaowordbill.url
     *
     * @return the value of t_taobaowordbill.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_taobaowordbill.url
     *
     * @param url the value for t_taobaowordbill.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}