package com.bingblue.TaobaoTools.mapper;

import com.bingblue.TaobaoTools.pojo.AnalyzeStoreBill;
import com.bingblue.TaobaoTools.pojo.AnalyzeStoreBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnalyzeStoreBillMapper {
	//自定义Start
    List<AnalyzeStoreBill> selectByExampleLimit(AnalyzeStoreBillExample example);
    //自定义End
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestorebill
     *
     * @mbg.generated
     */
    long countByExample(AnalyzeStoreBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestorebill
     *
     * @mbg.generated
     */
    int deleteByExample(AnalyzeStoreBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestorebill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestorebill
     *
     * @mbg.generated
     */
    int insert(AnalyzeStoreBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestorebill
     *
     * @mbg.generated
     */
    int insertSelective(AnalyzeStoreBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestorebill
     *
     * @mbg.generated
     */
    List<AnalyzeStoreBill> selectByExample(AnalyzeStoreBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestorebill
     *
     * @mbg.generated
     */
    AnalyzeStoreBill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestorebill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AnalyzeStoreBill record, @Param("example") AnalyzeStoreBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestorebill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AnalyzeStoreBill record, @Param("example") AnalyzeStoreBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestorebill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AnalyzeStoreBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestorebill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AnalyzeStoreBill record);
}