package com.bingblue.TaobaoTools.mapper;

import com.bingblue.TaobaoTools.pojo.AnalyzeStoreDetail;
import com.bingblue.TaobaoTools.pojo.AnalyzeStoreDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnalyzeStoreDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    long countByExample(AnalyzeStoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    int deleteByExample(AnalyzeStoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    int insert(AnalyzeStoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    int insertSelective(AnalyzeStoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    List<AnalyzeStoreDetail> selectByExample(AnalyzeStoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    AnalyzeStoreDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AnalyzeStoreDetail record, @Param("example") AnalyzeStoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AnalyzeStoreDetail record, @Param("example") AnalyzeStoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AnalyzeStoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_analyzestoredetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AnalyzeStoreDetail record);
}