package com.bingblue.TaobaoTools.mapper;

import com.bingblue.TaobaoTools.pojo.LocalCookie;
import com.bingblue.TaobaoTools.pojo.LocalCookieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocalCookieMapper {
    //mycode start
    int updateByTypeOtherSelective(LocalCookie localCookie);
    //mycode end
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localcookie
     *
     * @mbg.generated
     */
    long countByExample(LocalCookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localcookie
     *
     * @mbg.generated
     */
    int deleteByExample(LocalCookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localcookie
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localcookie
     *
     * @mbg.generated
     */
    int insert(LocalCookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localcookie
     *
     * @mbg.generated
     */
    int insertSelective(LocalCookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localcookie
     *
     * @mbg.generated
     */
    List<LocalCookie> selectByExample(LocalCookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localcookie
     *
     * @mbg.generated
     */
    LocalCookie selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localcookie
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LocalCookie record, @Param("example") LocalCookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localcookie
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LocalCookie record, @Param("example") LocalCookieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localcookie
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LocalCookie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localcookie
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LocalCookie record);
}