package com.bingblue.TaobaoTools.mapper;

import com.bingblue.TaobaoTools.pojo.ManyOrderBill;
import com.bingblue.TaobaoTools.pojo.ManyOrderBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManyOrderBillMapper {
    //自定义Start
    ManyOrderBill selectOneHasDetails(Long id);
    
    List<ManyOrderBill> selectByExampleLimit(ManyOrderBillExample example);
    //自定义End
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manyorderbill
     *
     * @mbg.generated
     */
    long countByExample(ManyOrderBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manyorderbill
     *
     * @mbg.generated
     */
    int deleteByExample(ManyOrderBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manyorderbill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manyorderbill
     *
     * @mbg.generated
     */
    int insert(ManyOrderBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manyorderbill
     *
     * @mbg.generated
     */
    int insertSelective(ManyOrderBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manyorderbill
     *
     * @mbg.generated
     */
    List<ManyOrderBill> selectByExample(ManyOrderBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manyorderbill
     *
     * @mbg.generated
     */
    ManyOrderBill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manyorderbill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManyOrderBill record, @Param("example") ManyOrderBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manyorderbill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManyOrderBill record, @Param("example") ManyOrderBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manyorderbill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManyOrderBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manyorderbill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManyOrderBill record);
}