package com.bingblue.TaobaoTools.mapper;

import com.bingblue.TaobaoTools.pojo.StuckFirstScreenBill;
import com.bingblue.TaobaoTools.pojo.StuckFirstScreenBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StuckFirstScreenBillMapper {
    //mycode start
    List<StuckFirstScreenBill> selectHasTaobaoWord(StuckFirstScreenBillExample example);
    StuckFirstScreenBill selectOneHasTaobaoWord(StuckFirstScreenBillExample example);
    //mycode end
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stuckfirstscreenbill
     *
     * @mbg.generated
     */
    long countByExample(StuckFirstScreenBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stuckfirstscreenbill
     *
     * @mbg.generated
     */
    int deleteByExample(StuckFirstScreenBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stuckfirstscreenbill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stuckfirstscreenbill
     *
     * @mbg.generated
     */
    int insert(StuckFirstScreenBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stuckfirstscreenbill
     *
     * @mbg.generated
     */
    int insertSelective(StuckFirstScreenBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stuckfirstscreenbill
     *
     * @mbg.generated
     */
    List<StuckFirstScreenBill> selectByExample(StuckFirstScreenBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stuckfirstscreenbill
     *
     * @mbg.generated
     */
    StuckFirstScreenBill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stuckfirstscreenbill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StuckFirstScreenBill record, @Param("example") StuckFirstScreenBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stuckfirstscreenbill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StuckFirstScreenBill record, @Param("example") StuckFirstScreenBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stuckfirstscreenbill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StuckFirstScreenBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stuckfirstscreenbill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StuckFirstScreenBill record);
}