package com.bingblue.TaobaoTools.mapper;

import com.bingblue.TaobaoTools.pojo.TaobaoShopProduct;
import com.bingblue.TaobaoTools.pojo.TaobaoShopProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaobaoShopProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    long countByExample(TaobaoShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    int deleteByExample(TaobaoShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    int insert(TaobaoShopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    int insertSelective(TaobaoShopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    List<TaobaoShopProduct> selectByExample(TaobaoShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    TaobaoShopProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaobaoShopProduct record, @Param("example") TaobaoShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaobaoShopProduct record, @Param("example") TaobaoShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaobaoShopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_taobaoshopproduct
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaobaoShopProduct record);
}